# Local 환경 전용 설정
# 공통 설정은 application.yaml 참조

logging:
  level:
    root: info
    server.poptato.global.exception: debug
    server.poptato.auth.application.service: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
