# Prod 환경 전용 설정
# 공통 설정은 application.yaml

logging:
  level:
    root: info
    server.poptato.global.exception: warn
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
